### PR TITLE
fixed gth config scripts to take into account miniPOD links and fix OH10 link0

### PR DESCRIPTION
**Pull request by evka85**
When we started using miniPOD links for trigger inputs in v3.7.2, Laurent noticed that OH10 link0 was not working, this was traced to a bug introduced long time ago which resulted in two miniPOD channels to not be configured at all (those are one of few channels that need RX inversion), so they defaulted to powered-off state. One of those two channels is unused, and the other one is OH10 link0.

## Description

The fix is very simple -- use the actual address of the channel instead of hardcoded channel 11 address (which was the only one needing RX inversion before miniPOD links were introduced).

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

OH10 link0 is not working without this fix

## How Has This Been Tested?

Trigger loopback setup at TAMU. Laurent will test this with real hardware.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bdorney** [comment]
I've labeled this as `in progress` until we hear back from @lpetre-ulb

**Comment by jsturdy** [comment]
I don't know when these files were added here, but I see they have also been changed in `GEM_AMC` --- changing a script in two locations is asking for an error. This underlies why these scripts should be a separate entity unto themselves.  The way I see it we have two "good" options (and possibly other less good options)
* The scripts remain solely in `GEM_AMC`, but are packaged into an installable (RPM, which I think was something that was on the roadmap for the CTP7 FW to ease dependencies)
* A separate repository that is a submodule of `gemctp7user` and `GEM_AMC`

**Comment by evka85** [comment]
Yeah I wasn't sure where these files are being taken from these days.. I first changed it in GEM_AMC, but then noticed that they're here too. Do we have a script that's setting up everything in CTP7 yet? If yes, where is it taking these scripts from?

Having a dedicated repository just for these few scripts seems overkill to me. Since these are very low level things, I'm happy to keep them in GEM_AMC, and zip them up in release page for each release.

**Comment by jsturdy** [comment]
OK, I'd suggest an RPM, as we're configuring the CTP7s to use a package manager.
If you don't want to to this yourself, I can whip up a `Makefile` and `spec` file template, and then we can define what goes in the RPM and where/how.

**Comment by lpetre-ulb** [comment]
> I've labeled this as `in progress` until we hear back from @lpetre-ulb

As I emailed, the fix seems to be effective. I have tested OH10 as well as OH0, OH5 & OH7 in order to quickly test if the patch didn't cause problems elsewhere (even if it shouldn't).

**Comment by mexanick** [comment]
I'm going to merge it as it doesn't harm and is required for current functionality. Later we will put the script in one place only to assure proper packaging and integration.

**Review by mexanick — APPROVED** [review]

**Pull request merged**
